/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetopoo.gui;

import com.mycompany.projetopoo.Atendimento.Triagem;
import com.mycompany.projetopoo.Pessoas.Enfermeiro;
import com.mycompany.projetopoo.Pessoas.Paciente;

/**
 *
 * @author suKarolainy
 */
public class TriagemPaciente extends javax.swing.JFrame {

    /**
     * Creates new form TriagemPaciente
     */
    public TriagemPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enftriLbl = new javax.swing.JLabel();
        prioLbl = new javax.swing.JLabel();
        natendLbl = new javax.swing.JLabel();
        enftTxt = new javax.swing.JTextField();
        prioridadeTxt = new javax.swing.JTextField();
        motivoatendimentoTxt = new javax.swing.JTextField();
        SalvarBtn = new javax.swing.JButton();
        tsanguineoLbl = new javax.swing.JLabel();
        alergiaLbl = new javax.swing.JLabel();
        doencasLbl = new javax.swing.JLabel();
        medicamentoLbl = new javax.swing.JLabel();
        urgenteBtn = new javax.swing.JRadioButton();
        urgenteLbl = new javax.swing.JLabel();
        tsanguineoTxt = new javax.swing.JTextField();
        alergiaTxt = new javax.swing.JTextField();
        doencasTxt = new javax.swing.JTextField();
        medicamentoTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Triagem");

        enftriLbl.setText("Enfermeiro responsável:");

        prioLbl.setText("Prioridade:");

        natendLbl.setText("Motivo atendimento:");

        SalvarBtn.setText("Salvar");
        SalvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBtnActionPerformed(evt);
            }
        });

        tsanguineoLbl.setText("Tipo sanguíneo:");

        alergiaLbl.setText("Alergias:");

        doencasLbl.setText("Doenças crônicas:");

        medicamentoLbl.setText("Medicamentos controlados:");

        urgenteLbl.setText("Paciente necessita atendimento urgente?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(SalvarBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(urgenteLbl)
                                .addGap(18, 18, 18)
                                .addComponent(urgenteBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enftriLbl)
                                    .addComponent(prioLbl)
                                    .addComponent(natendLbl)
                                    .addComponent(tsanguineoLbl)
                                    .addComponent(alergiaLbl)
                                    .addComponent(doencasLbl)
                                    .addComponent(medicamentoLbl))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tsanguineoTxt)
                                    .addComponent(alergiaTxt)
                                    .addComponent(doencasTxt)
                                    .addComponent(medicamentoTxt)
                                    .addComponent(enftTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prioridadeTxt)
                                    .addComponent(motivoatendimentoTxt))))))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enftriLbl)
                    .addComponent(enftTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prioLbl)
                    .addComponent(prioridadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(natendLbl)
                    .addComponent(motivoatendimentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tsanguineoLbl)
                    .addComponent(tsanguineoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alergiaLbl)
                    .addComponent(alergiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doencasLbl)
                    .addComponent(doencasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicamentoLbl)
                    .addComponent(medicamentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urgenteLbl)
                    .addComponent(urgenteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(SalvarBtn)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBtnActionPerformed
        // TODO add your handling code here:
        //enf prioridade motivo atendimento =- sangue - alergia - doenca - remedio -urgente 
        Enfermeiro enfermeiro = new Enfermeiro();
        Triagem triagem = new Triagem();
        Paciente paciente = new Paciente();
        
        enfermeiro.setNome(enftTxt.getText());
        triagem.setEnfermeiroTriador(enfermeiro);
        triagem.setPrioridadeAtendimento(prioridadeTxt.getText());
        triagem.setMotivoAtendimento(motivoatendimentoTxt.getText());
        
        paciente.setTipoSanguineo(tsanguineoTxt.getText());
        paciente.setAlergia(alergiaTxt.getText());
        paciente.setDoencasCronicas(doencasTxt.getText());
        paciente.setRemediosControlados(medicamentoTxt.getText());
        //paciente.setEstado(urgenteBtn.getAutoscrolls());
        
        //triagem.getPaciente().getTipoSanguineo(tsanguineoTxt.getText());
        //triagem.getPaciente().getAlergia(alergiaTxt.getText());
        triagem.setPaciente(paciente);
        
        System.out.println("\nDados da triagem salvos!");
        System.out.println("\nEnfermeiro triador: " + triagem.getEnfermeiroTriador().getNome());
        System.out.println("\nPrioridade: " + triagem.getPrioridadeAtendimento());
        System.out.println("\nMotivo do atendimento: " + triagem.getMotivoAtendimento());
        System.out.println("\nDados do paciente: " + triagem.getPaciente());

        
    }//GEN-LAST:event_SalvarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TriagemPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TriagemPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TriagemPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TriagemPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TriagemPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalvarBtn;
    private javax.swing.JLabel alergiaLbl;
    private javax.swing.JTextField alergiaTxt;
    private javax.swing.JLabel doencasLbl;
    private javax.swing.JTextField doencasTxt;
    private javax.swing.JTextField enftTxt;
    private javax.swing.JLabel enftriLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel medicamentoLbl;
    private javax.swing.JTextField medicamentoTxt;
    private javax.swing.JTextField motivoatendimentoTxt;
    private javax.swing.JLabel natendLbl;
    private javax.swing.JLabel prioLbl;
    private javax.swing.JTextField prioridadeTxt;
    private javax.swing.JLabel tsanguineoLbl;
    private javax.swing.JTextField tsanguineoTxt;
    private javax.swing.JRadioButton urgenteBtn;
    private javax.swing.JLabel urgenteLbl;
    // End of variables declaration//GEN-END:variables
}
